# Generated by Django 4.2 on 2026-07-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_porterprofile_assigned_farmers'),
    ]

    operations = [
        migrations.AddField(
            model_name='porterprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
