# Generated by Django 4.2 on 2026-07-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_porterprofile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerprofile',
            old_name='numer_of_cows',
            new_name='number_of_cows',
        ),
    ]
