# Generated by Django 4.2 on 2026-07-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='milkcollection',
            name='session',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening')], max_length=10),
        ),
    ]
